workflows:
  ios-workflow:
    name: Build iOS IPA

    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --release --no-codesign
      - mkdir -p build/ios/ipa
      - cd build/ios/iphoneos
      - zip -r ../ipa/Runner.ipa Runner.app

    artifacts:
      - build/ios/ipa/*.ipa